#ifndef _XTB_SHORTHANDS_H_
#define _XTB_SHORTHANDS_H_

#ifndef XTB_STR_SHORTHANDS
#define XTB_STR_SHORTHANDS
#endif

#ifndef XTB_ALLOCATOR_SHORTHANDS
#define XTB_ALLOCATOR_SHORTHANDS
#endif

#ifndef XTB_ARENA_SHORTHANDS
#define XTB_ARENA_SHORTHANDS
#endif

#ifndef XTB_THREAD_CONTEXT_SHORTHANDS
#define XTB_THREAD_CONTEXT_SHORTHANDS
#endif

#endif // _XTB_SHORTHANDS_H_
