#ifndef _XTB_SHORTHANDS_H_
#define _XTB_SHORTHANDS_H_

#ifndef XTB_STR_SHORTHAND
#define XTB_STR_SHORTHAND
#endif

#ifndef XTB_ALLOCATOR_SHORTHAND
#define XTB_ALLOCATOR_SHORTHAND
#endif

#ifndef XTB_ARENA_SHORTHAND
#define XTB_ARENA_SHORTHAND
#endif

#ifndef XTB_THREAD_CONTEXT_SHORTHAND
#define XTB_THREAD_CONTEXT_SHORTHAND
#endif

#endif // _XTB_SHORTHANDS_H_
